package types

type CHIP string

type CPUID string

const (
	C486                   CHIP = "486"                       // (alias configured by machine type)
	C486V1                 CHIP = "486-v1"                    //
	Broadwell              CHIP = "Broadwell"                 // (alias configured by machine type)
	BroadwellIBRS          CHIP = "Broadwell-IBRS"            // (alias of Broadwell-v3)
	BroadwellNoTSX         CHIP = "Broadwell-noTSX"           // (alias of Broadwell-v2)
	BroadwellNoTSXIBRS     CHIP = "Broadwell-noTSX-IBRS"      // (alias of Broadwell-v4)
	BroadwellV1            CHIP = "Broadwell-v1"              // Intel Core Processor (Broadwell)
	BroadwellV2            CHIP = "Broadwell-v2"              // Intel Core Processor (Broadwell, no TSX)
	BroadwellV3            CHIP = "Broadwell-v3"              // Intel Core Processor (Broadwell, IBRS)
	BroadwellV4            CHIP = "Broadwell-v4"              // Intel Core Processor (Broadwell, no TSX, IBRS)
	CascadelakeServer      CHIP = "Cascadelake-Server"        // (alias configured by machine type)
	CascadelakeServerNoTSX CHIP = "Cascadelake-Server-noTSX"  // (alias of Cascadelake-Server-v3)
	CascadelakeServerV1    CHIP = "Cascadelake-Server-v1"     // Intel Xeon Processor (Cascadelake)
	CascadelakeServerV2    CHIP = "Cascadelake-Server-v2"     // Intel Xeon Processor (Cascadelake) [ARCH_CAPABILITIES]
	CascadelakeServerV3    CHIP = "Cascadelake-Server-v3"     // Intel Xeon Processor (Cascadelake) [ARCH_CAPABILITIES, no TSX]
	CascadelakeServerV4    CHIP = "Cascadelake-Server-v4"     // Intel Xeon Processor (Cascadelake) [ARCH_CAPABILITIES, EPT switching, no TSX]
	CascadelakeServerV5    CHIP = "Cascadelake-Server-v5"     // Intel Xeon Processor (Cascadelake) [ARCH_CAPABILITIES, EPT switching, XSAVES, no TSX]
	ClearwaterForest       CHIP = "ClearwaterForest"          // (alias configured by machine type)
	ClearwaterForestV1     CHIP = "ClearwaterForest-v1"       // Intel Xeon Processor (ClearwaterForest)
	Conroe                 CHIP = "Conroe"                    // (alias configured by machine type)
	ConroeV1               CHIP = "Conroe-v1"                 // Intel Celeron_4x0 (Conroe/Merom Class Core 2)
	Cooperlake             CHIP = "Cooperlake"                // (alias configured by machine type)
	CooperlakeV1           CHIP = "Cooperlake-v1"             // Intel Xeon Processor (Cooperlake)
	CooperlakeV2           CHIP = "Cooperlake-v2"             // Intel Xeon Processor (Cooperlake) [XSAVES]
	Denverton              CHIP = "Denverton"                 // (alias configured by machine type)
	DenvertonV1            CHIP = "Denverton-v1"              // Intel Atom Processor (Denverton)
	DenvertonV2            CHIP = "Denverton-v2"              // Intel Atom Processor (Denverton) [no MPX, no MONITOR]
	DenvertonV3            CHIP = "Denverton-v3"              // Intel Atom Processor (Denverton) [XSAVES, no MPX, no MONITOR]
	Dhyana                 CHIP = "Dhyana"                    // (alias configured by machine type)
	DhyanaV1               CHIP = "Dhyana-v1"                 // Hygon Dhyana Processor
	DhyanaV2               CHIP = "Dhyana-v2"                 // Hygon Dhyana Processor [XSAVES]
	EPYC                   CHIP = "EPYC"                      // (alias configured by machine type)
	EPYCGenoa              CHIP = "EPYC-Genoa"                // (alias configured by machine type)
	EPYCGenoaV1            CHIP = "EPYC-Genoa-v1"             // AMD EPYC-Genoa Processor
	EPYCIBPB               CHIP = "EPYC-IBPB"                 // (alias of EPYC-v2)
	EPYCMilan              CHIP = "EPYC-Milan"                // (alias configured by machine type)
	EPYCMilanV1            CHIP = "EPYC-Milan-v1"             // AMD EPYC-Milan Processor
	EPYCMilanV2            CHIP = "EPYC-Milan-v2"             // AMD EPYC-Milan-v2 Processor
	EPYCRome               CHIP = "EPYC-Rome"                 // (alias configured by machine type)
	EPYCRomeV1             CHIP = "EPYC-Rome-v1"              // AMD EPYC-Rome Processor
	EPYCRomeV2             CHIP = "EPYC-Rome-v2"              // AMD EPYC-Rome Processor
	EPYCRomeV3             CHIP = "EPYC-Rome-v3"              // AMD EPYC-Rome-v3 Processor
	EPYCRomeV4             CHIP = "EPYC-Rome-v4"              // AMD EPYC-Rome-v4 Processor (no XSAVES)
	EPYCV1                 CHIP = "EPYC-v1"                   // AMD EPYC Processor
	EPYCV2                 CHIP = "EPYC-v2"                   // AMD EPYC Processor (with IBPB)
	EPYCV3                 CHIP = "EPYC-v3"                   // AMD EPYC Processor
	EPYCV4                 CHIP = "EPYC-v4"                   // AMD EPYC-v4 Processor
	GraniteRapids          CHIP = "GraniteRapids"             // (alias configured by machine type)
	GraniteRapidsV1        CHIP = "GraniteRapids-v1"          // Intel Xeon Processor (GraniteRapids)
	GraniteRapidsV2        CHIP = "GraniteRapids-v2"          // Intel Xeon Processor (GraniteRapids)
	Haswell                CHIP = "Haswell"                   // (alias configured by machine type)
	HaswellIBRS            CHIP = "Haswell-IBRS"              // (alias of Haswell-v3)
	HaswellNoTSX           CHIP = "Haswell-noTSX"             // (alias of Haswell-v2)
	HaswellNoTSXIBRS       CHIP = "Haswell-noTSX-IBRS"        // (alias of Haswell-v4)
	HaswellV1              CHIP = "Haswell-v1"                // Intel Core Processor (Haswell)
	HaswellV2              CHIP = "Haswell-v2"                // Intel Core Processor (Haswell, no TSX)
	HaswellV3              CHIP = "Haswell-v3"                // Intel Core Processor (Haswell, IBRS)
	HaswellV4              CHIP = "Haswell-v4"                // Intel Core Processor (Haswell, no TSX, IBRS)
	IcelakeServer          CHIP = "Icelake-Server"            // (alias configured by machine type)
	IcelakeServernoTSX     CHIP = "Icelake-Server-noTSX"      // (alias of Icelake-Server-v2)
	IcelakeServerV1        CHIP = "Icelake-Server-v1"         // Intel Xeon Processor (Icelake)
	IcelakeServerV2        CHIP = "Icelake-Server-v2"         // Intel Xeon Processor (Icelake) [no TSX]
	IcelakeServerV3        CHIP = "Icelake-Server-v3"         // Intel Xeon Processor (Icelake)
	IcelakeServerV4        CHIP = "Icelake-Server-v4"         // Intel Xeon Processor (Icelake)
	IcelakeServerV5        CHIP = "Icelake-Server-v5"         // Intel Xeon Processor (Icelake) [XSAVES]
	IcelakeServerV6        CHIP = "Icelake-Server-v6"         // Intel Xeon Processor (Icelake) [5-level EPT]
	IcelakeServerV7        CHIP = "Icelake-Server-v7"         // Intel Xeon Processor (Icelake) [TSX, taa-no]
	IvyBridge              CHIP = "IvyBridge"                 // (alias configured by machine type)
	IvyBridgeIBRS          CHIP = "IvyBridge-IBRS"            // (alias of IvyBridge-v2)
	IvyBridgeV1            CHIP = "IvyBridge-v1"              // Intel Xeon E3-12xx v2 (Ivy Bridge)
	IvyBridgeV2            CHIP = "IvyBridge-v2"              // Intel Xeon E3-12xx v2 (Ivy Bridge, IBRS)
	KnightsMill            CHIP = "KnightsMill"               // (alias configured by machine type)
	KnightsMillV1          CHIP = "KnightsMill-v1"            // Intel Xeon Phi Processor (Knights Mill)
	Nehalem                CHIP = "Nehalem"                   // (alias configured by machine type)
	NehalemIBRS            CHIP = "Nehalem-IBRS"              // (alias of Nehalem-v2)
	NehalemV1              CHIP = "Nehalem-v1"                // Intel Core i7 9xx (Nehalem Class Core i7)
	NehalemV2              CHIP = "Nehalem-v2"                // Intel Core i7 9xx (Nehalem Core i7, IBRS update)
	OpteronG1              CHIP = "Opteron-G1"                // (alias configured by machine type)
	OpteronG1V1            CHIP = "Opteron_G1-v1"             // AMD Opteron 240 (Gen 1 Class Opteron)
	OpteronG2              CHIP = "Opteron_G2"                // (alias configured by machine type)
	OpteronG2V1            CHIP = "Opteron_G2-v1"             // AMD Opteron 22xx (Gen 2 Class Opteron)
	OpteronG3              CHIP = "Opteron_G3"                // (alias configured by machine type)
	OpteronG3V1            CHIP = "Opteron_G3-v1"             // AMD Opteron 23xx (Gen 3 Class Opteron)
	OpteronG4              CHIP = "Opteron_G4"                // (alias configured by machine type)
	OpteronG4V1            CHIP = "Opteron_G4-v1"             // AMD Opteron 62xx class CPU
	OpteronG5              CHIP = "Opteron_G5"                // (alias configured by machine type)
	OpteronG5V1            CHIP = "Opteron_G5-v1"             // AMD Opteron 63xx class CPU
	Penryn                 CHIP = "Penryn"                    // (alias configured by machine type)
	PenrynV1               CHIP = "Penryn-v1"                 // Intel Core 2 Duo P9xxx (Penryn Class Core 2)
	SandyBridge            CHIP = "SandyBridge"               // (alias configured by machine type)
	SandyBridgeIBRS        CHIP = "SandyBridge-IBRS"          // (alias of SandyBridge-v2)
	SandyBridgeV1          CHIP = "SandyBridge-v1"            // Intel Xeon E312xx (Sandy Bridge)
	SandyBridgeV2          CHIP = "SandyBridge-v2"            // Intel Xeon E312xx (Sandy Bridge, IBRS update)
	SapphireRapids         CHIP = "SapphireRapids"            // (alias configured by machine type)
	SapphireRapidsV1       CHIP = "SapphireRapids-v1"         // Intel Xeon Processor (SapphireRapids)
	SapphireRapidsV2       CHIP = "SapphireRapids-v2"         // Intel Xeon Processor (SapphireRapids)
	SapphireRapidsV3       CHIP = "SapphireRapids-v3"         // Intel Xeon Processor (SapphireRapids)
	SierraForest           CHIP = "SierraForest"              // (alias configured by machine type)
	SierraForestV1         CHIP = "SierraForest-v1"           // Intel Xeon Processor (SierraForest)
	SierraForestV2         CHIP = "SierraForest-v2"           // Intel Xeon Processor (SierraForest)
	SkylakeClient          CHIP = "Skylake-Client"            // (alias configured by machine type)
	SkylakeClientIBRS      CHIP = "Skylake-Client-IBRS"       // (alias of Skylake-Client-v2)
	SkylakeClientNoTSXIBRS CHIP = "Skylake-Client-noTSX-IBRS" // (alias of Skylake-Client-v3)
	SkylakeClientV1        CHIP = "Skylake-Client-v1"         // Intel Core Processor (Skylake)
	SkylakeClientV2        CHIP = "Skylake-Client-v2"         // Intel Core Processor (Skylake, IBRS)
	SkylakeClientV3        CHIP = "Skylake-Client-v3"         // Intel Core Processor (Skylake, IBRS, no TSX)
	SkylakeClientV4        CHIP = "Skylake-Client-v4"         // Intel Core Processor (Skylake, IBRS, no TSX) [IBRS, XSAVES, no TSX]
	SkylakeServer          CHIP = "Skylake-Server"            // (alias configured by machine type)
	SkylakeServerIBRS      CHIP = "Skylake-Server-IBRS"       // (alias of Skylake-Server-v2)
	SkylakeServerNoTSXIBRS CHIP = "Skylake-Server-noTSX-IBRS" // (alias of Skylake-Server-v3)
	SkylakeServerV1        CHIP = "Skylake-Server-v1"         // Intel Xeon Processor (Skylake)
	SkylakeServerV2        CHIP = "Skylake-Server-v2"         // Intel Xeon Processor (Skylake, IBRS)
	SkylakeServerV3        CHIP = "Skylake-Server-v3"         // Intel Xeon Processor (Skylake, IBRS, no TSX)
	SkylakeServerV4        CHIP = "Skylake-Server-v4"         // Intel Xeon Processor (Skylake, IBRS, no TSX) [IBRS, EPT switching, no TSX]
	SkylakeServerV5        CHIP = "Skylake-Server-v5"         // Intel Xeon Processor (Skylake, IBRS, no TSX) [IBRS, XSAVES, EPT switching, no TSX]
	Snowridge              CHIP = "Snowridge"                 // (alias configured by machine type)
	SnowridgeV1            CHIP = "Snowridge-v1"              // Intel Atom Processor (SnowRidge)
	SnowridgeV2            CHIP = "Snowridge-v2"              // Intel Atom Processor (Snowridge, no MPX)
	SnowridgeV3            CHIP = "Snowridge-v3"              // Intel Atom Processor (Snowridge, no MPX) [XSAVES, no MPX]
	SnowridgeV4            CHIP = "Snowridge-v4"              // Intel Atom Processor (Snowridge, no MPX) [no split lock detect, no core-capability]
	Westmere               CHIP = "Westmere"                  // (alias configured by machine type)
	WestmereIBRS           CHIP = "Westmere-IBRS"             // (alias of Westmere-v2)
	WestmereV1             CHIP = "Westmere-v1"               // Westmere E56xx/L56xx/X56xx (Nehalem-C)
	WestmereV2             CHIP = "Westmere-v2"               // Westmere E56xx/L56xx/X56xx (IBRS update)
	Athlon                 CHIP = "athlon"                    // (alias configured by machine type)
	AthlonV1               CHIP = "athlon-v1"                 // QEMU Virtual CPU version 2.5+
	Core2duo               CHIP = "core2duo"                  // (alias configured by machine type)
	Core2duoV1             CHIP = "core2duo-v1"               // Intel(R) Core(TM)2 Duo CPU     T7700  @ 2.40GHz
	Coreduo                CHIP = "coreduo"                   // (alias configured by machine type)
	CoreduoV1              CHIP = "coreduo-v1"                // Genuine Intel(R) CPU           T2600  @ 2.16GHz
	Kvm32                  CHIP = "kvm32"                     // (alias configured by machine type)
	Kvm32V1                CHIP = "kvm32-v1"                  // Common 32-bit KVM processor
	Kvm64                  CHIP = "kvm64"                     // (alias configured by machine type)
	Kvm64V1                CHIP = "kvm64-v1"                  // Common KVM processor
	N270                   CHIP = "n270"                      // (alias configured by machine type)
	N270V1                 CHIP = "n270-v1"                   // Intel(R) Atom(TM) CPU N270   @ 1.60GHz
	Pentium                CHIP = "pentium"                   // (alias configured by machine type)
	PentiumV1              CHIP = "pentium-v1"                // Intel(R) Pentium(R) CPU E3600  @ 2.40GHz
	Pentium2               CHIP = "pentium2"                  // (alias configured by machine type)
	Pentium2V1             CHIP = "pentium2-v1"               // Intel(R) Pentium(R) CPU E3600  @ 2.40GHz
	Pentium3               CHIP = "pentium3"                  // (alias configured by machine type)
	Pentium3V1             CHIP = "pentium3-v1"               // Intel(R) Pentium(R) CPU E3600  @ 2.40GHz
	Phenom                 CHIP = "phenom"                    // (alias configured by machine type)
	PhenomV1               CHIP = "phenom-v1"                 // AMD Phenom(tm) 9550 Quad-Core Processor
	Qqemu32                CHIP = "qemu32"                    // (alias configured by machine type)
	Qemu32V1               CHIP = "qemu32-v1"                 // QEMU Virtual CPU version 2.5+
	Qemu64                 CHIP = "qemu64"                    // (alias configured by machine type)
	Qemu64V1               CHIP = "qemu64-v1"                 // QEMU Virtual CPU version 2.5+
	Bbase                  CHIP = "base"                      // base CPU model type with no features enabled
	Max                    CHIP = "max"                       // Enables all features supported by the accelerator in the current host

	C3Dnow                          CPUID = "3dnow"
	C3Dnowext                       CPUID = "3dnowext"
	C3Dnowprefetch                  CPUID = "3dnowprefetch"
	Abm                             CPUID = "abm"
	Ace2                            CPUID = "ace2"
	Ace2En                          CPUID = "ace2-en"
	Acpi                            CPUID = "acpi"
	Adx                             CPUID = "adx"
	Aes                             CPUID = "aes"
	AmdNoSsb                        CPUID = "amd-no-ssb"
	AmdPsfd                         CPUID = "amd-psfd"
	AmdSsbd                         CPUID = "amd-ssbd"
	AmdStibp                        CPUID = "amd-stibp"
	AmxBf16                         CPUID = "amx-bf16"
	AmxComplex                      CPUID = "amx-complex"
	AmxFp16                         CPUID = "amx-fp16"
	AmxInt8                         CPUID = "amx-int8"
	AmxTile                         CPUID = "amx-tile"
	Apic                            CPUID = "apic"
	Arat                            CPUID = "arat"
	ArchCapabilities                CPUID = "arch-capabilities"
	ArchLbr                         CPUID = "arch-lbr"
	AutoIbrs                        CPUID = "auto-ibrs"
	Avic                            CPUID = "avic"
	Avx                             CPUID = "avx"
	AvxIfma                         CPUID = "avx-ifma"
	AvxNeConvert                    CPUID = "avx-ne-convert"
	AvxVnni                         CPUID = "avx-vnni"
	AvxVnniInt16                    CPUID = "avx-vnni-int16"
	AvxVnniInt8                     CPUID = "avx-vnni-int8"
	Avx10                           CPUID = "avx10"
	Avx10128                        CPUID = "avx10-128"
	Avx10256                        CPUID = "avx10-256"
	Avx10512                        CPUID = "avx10-512"
	Avx2                            CPUID = "avx2"
	Avx5124Fmaps                    CPUID = "avx512-4fmaps"
	Avx5124Vnniw                    CPUID = "avx512-4vnniw"
	Avx512Bf16                      CPUID = "avx512-bf16"
	Avx512Fp16                      CPUID = "avx512-fp16"
	Avx512Vp2intersect              CPUID = "avx512-vp2intersect"
	Avx512Vpopcntdq                 CPUID = "avx512-vpopcntdq"
	Avx512bitalg                    CPUID = "avx512bitalg"
	Avx512bw                        CPUID = "avx512bw"
	Avx512cd                        CPUID = "avx512cd"
	Avx512dq                        CPUID = "avx512dq"
	Avx512er                        CPUID = "avx512er"
	Avx512f                         CPUID = "avx512f"
	Avx512ifma                      CPUID = "avx512ifma"
	Avx512pf                        CPUID = "avx512pf"
	Avx512vbmi                      CPUID = "avx512vbmi"
	Avx512vbmi2                     CPUID = "avx512vbmi2"
	Avx512vl                        CPUID = "avx512vl"
	Avx512vnni                      CPUID = "avx512vnni"
	BhiCtrl                         CPUID = "bhi-ctrl"
	BhiNo                           CPUID = "bhi-no"
	Bmi1                            CPUID = "bmi1"
	Bmi2                            CPUID = "bmi2"
	BusLockDetect                   CPUID = "bus-lock-detect"
	Cid                             CPUID = "cid"
	Cldemote                        CPUID = "cldemote"
	Clflush                         CPUID = "clflush"
	Clflushopt                      CPUID = "clflushopt"
	Clwb                            CPUID = "clwb"
	Clzero                          CPUID = "clzero"
	Cmov                            CPUID = "cmov"
	CmpLegacy                       CPUID = "cmp-legacy"
	Cmpccxadd                       CPUID = "cmpccxadd"
	CoreCapability                  CPUID = "core-capability"
	Cr8legacy                       CPUID = "cr8legacy"
	Cx16                            CPUID = "cx16"
	Cx8                             CPUID = "cx8"
	Dca                             CPUID = "dca"
	DdpdU                           CPUID = "ddpd-u"
	De                              CPUID = "de"
	Decodeassists                   CPUID = "decodeassists"
	Ds                              CPUID = "ds"
	DsCpl                           CPUID = "ds-cpl"
	Dtes64                          CPUID = "dtes64"
	Eraps                           CPUID = "eraps"
	Erms                            CPUID = "erms"
	Est                             CPUID = "est"
	Extapic                         CPUID = "extapic"
	F16c                            CPUID = "f16c"
	FbClear                         CPUID = "fb-clear"
	FbsdpNo                         CPUID = "fbsdp-no"
	FdpExcptnOnly                   CPUID = "fdp-excptn-only"
	FlushL1d                        CPUID = "flush-l1d"
	Flushbyasid                     CPUID = "flushbyasid"
	Fma                             CPUID = "fma"
	Fma4                            CPUID = "fma4"
	Fpu                             CPUID = "fpu"
	Fred                            CPUID = "fred"
	Fsgsbase                        CPUID = "fsgsbase"
	Fsrc                            CPUID = "fsrc"
	Fsrm                            CPUID = "fsrm"
	Fsrs                            CPUID = "fsrs"
	FullWidthWrite                  CPUID = "full-width-write"
	Fxsr                            CPUID = "fxsr"
	FxsrOpt                         CPUID = "fxsr-opt"
	Fzrm                            CPUID = "fzrm"
	GdsNo                           CPUID = "gds-no"
	Gfni                            CPUID = "gfni"
	Hle                             CPUID = "hle"
	Ht                              CPUID = "ht"
	Hypervisor                      CPUID = "hypervisor"
	Ia64                            CPUID = "ia64"
	Ibpb                            CPUID = "ibpb"
	IbpbBrtype                      CPUID = "ibpb-brtype"
	Ibrs                            CPUID = "ibrs"
	IbrsAll                         CPUID = "ibrs-all"
	Ibs                             CPUID = "ibs"
	IntelPsfd                       CPUID = "intel-psfd"
	IntelPt                         CPUID = "intel-pt"
	IntelPtLip                      CPUID = "intel-pt-lip"
	Invpcid                         CPUID = "invpcid"
	Invtsc                          CPUID = "invtsc"
	IpredCtrl                       CPUID = "ipred-ctrl"
	KvmAsyncpf                      CPUID = "kvm-asyncpf"
	KvmAsyncpfInt                   CPUID = "kvm-asyncpf-int"
	KvmAsyncpfVmexit                CPUID = "kvm-asyncpf-vmexit"
	KvmHintDedicated                CPUID = "kvm-hint-dedicated"
	KvmMmu                          CPUID = "kvm-mmu"
	KvmMsiExtDestId                 CPUID = "kvm-msi-ext-dest-id"
	KvmNopiodelay                   CPUID = "kvm-nopiodelay"
	KvmPollControl                  CPUID = "kvm-poll-control"
	KvmPvEoi                        CPUID = "kvm-pv-eoi"
	KvmPvIpi                        CPUID = "kvm-pv-ipi"
	KvmPvSchedYield                 CPUID = "kvm-pv-sched-yield"
	KvmPvTlbFlush                   CPUID = "kvm-pv-tlb-flush"
	KvmPvUnhalt                     CPUID = "kvm-pv-unhalt"
	KvmStealTime                    CPUID = "kvm-steal-time"
	Kvmclock                        CPUID = "kvmclock"
	KvmclockStableBit               CPUID = "kvmclock-stable-bit"
	La57                            CPUID = "la57"
	LahfLm                          CPUID = "lahf-lm"
	Lam                             CPUID = "lam"
	Lbrv                            CPUID = "lbrv"
	LfenceAlwaysSerializing         CPUID = "lfence-always-serializing"
	Lkgs                            CPUID = "lkgs"
	Lm                              CPUID = "lm"
	Lwp                             CPUID = "lwp"
	Mca                             CPUID = "mca"
	McdtNo                          CPUID = "mcdt-no"
	Mce                             CPUID = "mce"
	MdClear                         CPUID = "md-clear"
	MdsNo                           CPUID = "mds-no"
	Misalignsse                     CPUID = "misalignsse"
	Mmx                             CPUID = "mmx"
	Mmxext                          CPUID = "mmxext"
	Monitor                         CPUID = "monitor"
	Movbe                           CPUID = "movbe"
	Movdir64b                       CPUID = "movdir64b"
	Movdiri                         CPUID = "movdiri"
	Mpx                             CPUID = "mpx"
	Msr                             CPUID = "msr"
	Mtrr                            CPUID = "mtrr"
	NoNestedDataBp                  CPUID = "no-nested-data-bp"
	NodeidMsr                       CPUID = "nodeid-msr"
	Npt                             CPUID = "npt"
	NripSave                        CPUID = "nrip-save"
	NullSelClrBase                  CPUID = "null-sel-clr-base"
	Nx                              CPUID = "nx"
	Osvw                            CPUID = "osvw"
	OverflowRecov                   CPUID = "overflow-recov"
	Pae                             CPUID = "pae"
	Pat                             CPUID = "pat"
	PauseFilter                     CPUID = "pause-filter"
	Pbe                             CPUID = "pbe"
	PbrsbNo                         CPUID = "pbrsb-no"
	Pcid                            CPUID = "pcid"
	Pclmulqdq                       CPUID = "pclmulqdq"
	Pcommit                         CPUID = "pcommit"
	Pdcm                            CPUID = "pdcm"
	Pdpe1gb                         CPUID = "pdpe1gb"
	PerfctrCore                     CPUID = "perfctr-core"
	PerfctrNb                       CPUID = "perfctr-nb"
	PerfmonV2                       CPUID = "perfmon-v2"
	Pfthreshold                     CPUID = "pfthreshold"
	Pge                             CPUID = "pge"
	Phe                             CPUID = "phe"
	PheEn                           CPUID = "phe-en"
	Pks                             CPUID = "pks"
	Pku                             CPUID = "pku"
	Pmm                             CPUID = "pmm"
	PmmEn                           CPUID = "pmm-en"
	Pn                              CPUID = "pn"
	Pni                             CPUID = "pni"
	Popcnt                          CPUID = "popcnt"
	Prefetchiti                     CPUID = "prefetchiti"
	PschangeMcNo                    CPUID = "pschange-mc-no"
	PsdpNo                          CPUID = "psdp-no"
	Pse                             CPUID = "pse"
	Pse36                           CPUID = "pse36"
	RdctlNo                         CPUID = "rdctl-no"
	Rdpid                           CPUID = "rdpid"
	Rdrand                          CPUID = "rdrand"
	Rdseed                          CPUID = "rdseed"
	Rdtscp                          CPUID = "rdtscp"
	RfdsClear                       CPUID = "rfds-clear"
	RfdsNo                          CPUID = "rfds-no"
	RrsbaCtrl                       CPUID = "rrsba-ctrl"
	Rsba                            CPUID = "rsba"
	Rtm                             CPUID = "rtm"
	SbdrSsdpNo                      CPUID = "sbdr-ssdp-no"
	Sbpb                            CPUID = "sbpb"
	Sep                             CPUID = "sep"
	Serialize                       CPUID = "serialize"
	Sgx                             CPUID = "sgx"
	SgxAexNotify                    CPUID = "sgx-aex-notify"
	SgxDebug                        CPUID = "sgx-debug"
	SgxEdeccssa                     CPUID = "sgx-edeccssa"
	SgxExinfo                       CPUID = "sgx-exinfo"
	SgxKss                          CPUID = "sgx-kss"
	SgxMode64                       CPUID = "sgx-mode64"
	SgxProvisionkey                 CPUID = "sgx-provisionkey"
	SgxTokenkey                     CPUID = "sgx-tokenkey"
	Sgx1                            CPUID = "sgx1"
	Sgx2                            CPUID = "sgx2"
	Sgxlc                           CPUID = "sgxlc"
	ShaNi                           CPUID = "sha-ni"
	Sha512                          CPUID = "sha512"
	Skinit                          CPUID = "skinit"
	SkipL1dflVmentry                CPUID = "skip-l1dfl-vmentry"
	Sm3                             CPUID = "sm3"
	Sm4                             CPUID = "sm4"
	Smap                            CPUID = "smap"
	Smep                            CPUID = "smep"
	Smx                             CPUID = "smx"
	SpecCtrl                        CPUID = "spec-ctrl"
	SplitLockDetect                 CPUID = "split-lock-detect"
	SrsoNo                          CPUID = "srso-no"
	SrsoUserKernelNo                CPUID = "srso-user-kernel-no"
	Ss                              CPUID = "ss"
	SsbNo                           CPUID = "ssb-no"
	Ssbd                            CPUID = "ssbd"
	Sse                             CPUID = "sse"
	Sse2                            CPUID = "sse2"
	Sse4_1                          CPUID = "sse4.1"
	Sse4_2                          CPUID = "sse4.2"
	Sse4a                           CPUID = "sse4a"
	Ssse3                           CPUID = "ssse3"
	Stibp                           CPUID = "stibp"
	StibpAlwaysOn                   CPUID = "stibp-always-on"
	Succor                          CPUID = "succor"
	Svm                             CPUID = "svm"
	SvmLock                         CPUID = "svm-lock"
	SvmeAddrChk                     CPUID = "svme-addr-chk"
	Syscall                         CPUID = "syscall"
	TaaNo                           CPUID = "taa-no"
	Tbm                             CPUID = "tbm"
	Tce                             CPUID = "tce"
	Tm                              CPUID = "tm"
	Tm2                             CPUID = "tm2"
	Topoext                         CPUID = "topoext"
	Tsc                             CPUID = "tsc"
	TscAdjust                       CPUID = "tsc-adjust"
	TscDeadline                     CPUID = "tsc-deadline"
	TscScale                        CPUID = "tsc-scale"
	TsxCtrl                         CPUID = "tsx-ctrl"
	TsxLdtrk                        CPUID = "tsx-ldtrk"
	Umip                            CPUID = "umip"
	VVmsaveVmload                   CPUID = "v-vmsave-vmload"
	Vaes                            CPUID = "vaes"
	Vgif                            CPUID = "vgif"
	VirtSsbd                        CPUID = "virt-ssbd"
	VmcbClean                       CPUID = "vmcb-clean"
	Vme                             CPUID = "vme"
	Vmx                             CPUID = "vmx"
	VmxActivityHlt                  CPUID = "vmx-activity-hlt"
	VmxActivityShutdown             CPUID = "vmx-activity-shutdown"
	VmxActivityWaitSipi             CPUID = "vmx-activity-wait-sipi"
	VmxAnyErrcode                   CPUID = "vmx-any-errcode"
	VmxApicvRegister                CPUID = "vmx-apicv-register"
	VmxApicvVid                     CPUID = "vmx-apicv-vid"
	VmxApicvX2apic                  CPUID = "vmx-apicv-x2apic"
	VmxApicvXapic                   CPUID = "vmx-apicv-xapic"
	VmxCr3LoadNoexit                CPUID = "vmx-cr3-load-noexit"
	VmxCr3StoreNoexit               CPUID = "vmx-cr3-store-noexit"
	VmxCr8LoadExit                  CPUID = "vmx-cr8-load-exit"
	VmxCr8StoreExit                 CPUID = "vmx-cr8-store-exit"
	VmxDescExit                     CPUID = "vmx-desc-exit"
	VmxEnableUserWaitPause          CPUID = "vmx-enable-user-wait-pause"
	VmxEnclsExit                    CPUID = "vmx-encls-exit"
	VmxEntryIa32eMode               CPUID = "vmx-entry-ia32e-mode"
	VmxEntryLoadBndcfgs             CPUID = "vmx-entry-load-bndcfgs"
	VmxEntryLoadEfer                CPUID = "vmx-entry-load-efer"
	VmxEntryLoadFred                CPUID = "vmx-entry-load-fred"
	VmxEntryLoadPat                 CPUID = "vmx-entry-load-pat"
	VmxEntryLoadPerfGlobalCtrl      CPUID = "vmx-entry-load-perf-global-ctrl"
	VmxEntryLoadPkrs                CPUID = "vmx-entry-load-pkrs"
	VmxEntryLoadRtitCtl             CPUID = "vmx-entry-load-rtit-ctl"
	VmxEntryNoloadDebugctl          CPUID = "vmx-entry-noload-debugctl"
	VmxEpt                          CPUID = "vmx-ept"
	VmxEpt1Gb                       CPUID = "vmx-ept-1gb"
	VmxEpt2Mb                       CPUID = "vmx-ept-2mb"
	VmxEptAdvancedExitinfo          CPUID = "vmx-ept-advanced-exitinfo"
	VmxEptExeconly                  CPUID = "vmx-ept-execonly"
	VmxEptad                        CPUID = "vmx-eptad"
	VmxEptpSwitching                CPUID = "vmx-eptp-switching"
	VmxExitAckIntr                  CPUID = "vmx-exit-ack-intr"
	VmxExitClearBndcfgs             CPUID = "vmx-exit-clear-bndcfgs"
	VmxExitClearRtitCtl             CPUID = "vmx-exit-clear-rtit-ctl"
	VmxExitLoadEfer                 CPUID = "vmx-exit-load-efer"
	VmxExitLoadPat                  CPUID = "vmx-exit-load-pat"
	VmxExitLoadPerfGlobalCtrl       CPUID = "vmx-exit-load-perf-global-ctrl"
	VmxExitLoadPkrs                 CPUID = "vmx-exit-load-pkrs"
	VmxExitNosaveDebugctl           CPUID = "vmx-exit-nosave-debugctl"
	VmxExitSaveEfer                 CPUID = "vmx-exit-save-efer"
	VmxExitSavePat                  CPUID = "vmx-exit-save-pat"
	VmxExitSavePreemptionTimer      CPUID = "vmx-exit-save-preemption-timer"
	VmxExitSecondaryCtls            CPUID = "vmx-exit-secondary-ctls"
	VmxFlexpriority                 CPUID = "vmx-flexpriority"
	VmxHltExit                      CPUID = "vmx-hlt-exit"
	VmxInsOuts                      CPUID = "vmx-ins-outs"
	VmxIntrExit                     CPUID = "vmx-intr-exit"
	VmxInvept                       CPUID = "vmx-invept"
	VmxInveptAllContext             CPUID = "vmx-invept-all-context"
	VmxInveptSingleContext          CPUID = "vmx-invept-single-context"
	VmxInveptSingleContextNoglobals CPUID = "vmx-invept-single-context-noglobals"
	VmxInvlpgExit                   CPUID = "vmx-invlpg-exit"
	VmxInvpcidExit                  CPUID = "vmx-invpcid-exit"
	VmxInvvpid                      CPUID = "vmx-invvpid"
	VmxInvvpidAllContext            CPUID = "vmx-invvpid-all-context"
	VmxInvvpidSingleAddr            CPUID = "vmx-invvpid-single-addr"
	VmxIoBitmap                     CPUID = "vmx-io-bitmap"
	VmxIoExit                       CPUID = "vmx-io-exit"
	VmxMonitorExit                  CPUID = "vmx-monitor-exit"
	VmxMovdrExit                    CPUID = "vmx-movdr-exit"
	VmxMsrBitmap                    CPUID = "vmx-msr-bitmap"
	VmxMtf                          CPUID = "vmx-mtf"
	VmxMwaitExit                    CPUID = "vmx-mwait-exit"
	VmxNestedException              CPUID = "vmx-nested-exception"
	VmxNmiExit                      CPUID = "vmx-nmi-exit"
	VmxPageWalk4                    CPUID = "vmx-page-walk-4"
	VmxPageWalk5                    CPUID = "vmx-page-walk-5"
	VmxPauseExit                    CPUID = "vmx-pause-exit"
	VmxPle                          CPUID = "vmx-ple"
	VmxPml                          CPUID = "vmx-pml"
	VmxPostedIntr                   CPUID = "vmx-posted-intr"
	VmxPreemptionTimer              CPUID = "vmx-preemption-timer"
	VmxRdpmcExit                    CPUID = "vmx-rdpmc-exit"
	VmxRdrandExit                   CPUID = "vmx-rdrand-exit"
	VmxRdseedExit                   CPUID = "vmx-rdseed-exit"
	VmxRdtscExit                    CPUID = "vmx-rdtsc-exit"
	VmxRdtscpExit                   CPUID = "vmx-rdtscp-exit"
	VmxSecondaryCtls                CPUID = "vmx-secondary-ctls"
	VmxShadowVmcs                   CPUID = "vmx-shadow-vmcs"
	VmxStoreLma                     CPUID = "vmx-store-lma"
	VmxTrueCtls                     CPUID = "vmx-true-ctls"
	VmxTscOffset                    CPUID = "vmx-tsc-offset"
	VmxTscScaling                   CPUID = "vmx-tsc-scaling"
	VmxUnrestrictedGuest            CPUID = "vmx-unrestricted-guest"
	VmxVintrPending                 CPUID = "vmx-vintr-pending"
	VmxVmfunc                       CPUID = "vmx-vmfunc"
	VmxVmwriteVmexitFields          CPUID = "vmx-vmwrite-vmexit-fields"
	VmxVnmi                         CPUID = "vmx-vnmi"
	VmxVnmiPending                  CPUID = "vmx-vnmi-pending"
	VmxVpid                         CPUID = "vmx-vpid"
	VmxWbinvdExit                   CPUID = "vmx-wbinvd-exit"
	VmxXsaves                       CPUID = "vmx-xsaves"
	VmxZeroLenInject                CPUID = "vmx-zero-len-inject"
	Vnmi                            CPUID = "vnmi"
	Vpclmulqdq                      CPUID = "vpclmulqdq"
	Waitpkg                         CPUID = "waitpkg"
	Wbnoinvd                        CPUID = "wbnoinvd"
	Wdt                             CPUID = "wdt"
	Wrmsrns                         CPUID = "wrmsrns"
	X2apic                          CPUID = "x2apic"
	Xcrypt                          CPUID = "xcrypt"
	XcryptEn                        CPUID = "xcrypt-en"
	Xfd                             CPUID = "xfd"
	Xgetbv1                         CPUID = "xgetbv1"
	Xop                             CPUID = "xop"
	Xsave                           CPUID = "xsave"
	Xsavec                          CPUID = "xsavec"
	Xsaveerptr                      CPUID = "xsaveerptr"
	Xsaveopt                        CPUID = "xsaveopt"
	Xsaves                          CPUID = "xsaves"
	Xstore                          CPUID = "xstore"
	XstoreEn                        CPUID = "xstore-en"
	Xtpr                            CPUID = "xtpr"
	ZeroFcsFds                      CPUID = "zero-fcs-fds"
)
